name = "mafclubdemo"
main = "worker.js"
compatibility_date = "2025-11-05"

# Статические файлы (HTML, JS, CSS)
[site]
bucket = "."

# D1 База данных
[[d1_databases]]
binding = "DB"
database_name = "mafia-rating"
database_id = "0493685a-cd3e-45d0-9627-6b3652dc31e3"
